app = "phx-lv-example"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[deploy]

[env]
  PORT = "4000"

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 2500
    soft_limit = 2000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443